apiVersion: v1
kind: Service
metadata:
  name: rickmorthumali1-internal-service
spec:
  type: NodePort 
  selector:
    app: rickmorthumali1
  ports:
    - nodePort: 31611
      port: 8080
      targetPort: 8080
